# Generated by Django 3.2 on 2024-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptfile',
            name='status',
            field=models.CharField(default='Failed To convert', max_length=100),
        ),
    ]
